// <auto-generated />
namespace TutorOnline.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addlogintable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlogintable));
        
        string IMigrationMetadata.Id
        {
            get { return "202002220932572_addlogintable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
