// <auto-generated />
namespace TutorOnline.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addDegreeColumninTeacher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDegreeColumninTeacher));
        
        string IMigrationMetadata.Id
        {
            get { return "202002222056485_addDegreeColumninTeacher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
